CREATE TABLE `ocr_results` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `application_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vida_request_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'VIDA transaction ID, permanent audit link',
  `raw_response` json NOT NULL COMMENT 'Full VIDA API response, never modified',
  `nik` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `full_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_place` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` enum('LAKI-LAKI','PEREMPUAN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` text COLLATE utf8mb4_unicode_ci,
  `rt_rw` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'e.g. "003/007"',
  `kelurahan` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kecamatan` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kabupaten_kota` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provinsi` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `religion` enum('ISLAM','KRISTEN','KATOLIK','HINDU','BUDDHA','KONGHUCU','Lainnya') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `marital_status` enum('BELUM KAWIN','KAWIN','CERAI HIDUP','CERAI MATI') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `occupation` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nationality` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'WNI',
  `expiry_date` date DEFAULT NULL COMMENT 'NULL = SEUMUR HIDUP',
  `confidence_score` decimal(5,4) DEFAULT NULL COMMENT 'Overall OCR confidence, e.g. 0.9823',
  `nik_confidence` decimal(5,4) DEFAULT NULL,
  `name_confidence` decimal(5,4) DEFAULT NULL,
  `ktp_image_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '/var/app/storage/ktp/{year}/{month}/{application_id}.jpg',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ocr_results_application` (`application_id`),
  UNIQUE KEY `uq_ocr_results_vida_req` (`vida_request_id`),
  KEY `idx_ocr_results_nik` (`nik`),
  CONSTRAINT `fk_ocr_results_application` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `liveness_results` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `application_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vida_request_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'VIDA server-side verification ID',
  `vida_session_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'VIDA Web SDK session token',
  `raw_response` json NOT NULL COMMENT 'Full VIDA API response, never modified',
  `liveness_status` enum('PASSED','FAILED','REVIEW') COLLATE utf8mb4_unicode_ci NOT NULL,
  `liveness_score` decimal(5,4) DEFAULT NULL COMMENT 'Anti-spoofing score, e.g. 0.9985',
  `face_match_status` enum('MATCHED','NOT_MATCHED','REVIEW') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `face_match_score` decimal(5,4) DEFAULT NULL COMMENT 'Similarity score between selfie and KTP photo',
  `fraud_status` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '001' COMMENT '001=in_progress, 002=submitted_manual, 003=accepted, 004=rejected, 006=cert_not_issued, 007=cert_issued',
  `kyc_event_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'VIDA event ID setelah fraud status 003 — dipakai sebagai kyc_event_id di Direct Sign',
  `selfie_image_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '/var/app/storage/selfie/{year}/{month}/{application_id}.jpg',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_liveness_results_application` (`application_id`),
  UNIQUE KEY `uq_liveness_results_vida_req` (`vida_request_id`),
  KEY `idx_liveness_fraud_status` (`fraud_status`),
  CONSTRAINT `fk_liveness_results_application` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contract_documents` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `application_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `document_type` enum('SAVING','DEPOSIT','LOAN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '/var/app/storage/contracts/{year}/{month}/{application_id}.pdf',
  `file_size_bytes` int unsigned DEFAULT NULL,
  `file_hash_sha256` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Integrity check for the generated PDF',
  `vida_document_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Document ID from VIDA after registration',
  `vida_sign_request_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Signing request ID from VIDA POA API',
  `emeterai_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'eMeterai stamp ID from VIDA',
  `emeterai_applied_at` datetime DEFAULT NULL,
  `sign_status` enum('PENDING','SIGNING','COMPLETED','FAILED','EXPIRED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `sign_link` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL sent to customer to complete signing',
  `sign_link_sent_at` datetime DEFAULT NULL,
  `sign_deadline` datetime DEFAULT NULL COMMENT 'Auto-set to 7 days after sign_link_sent_at',
  `signed_at` datetime DEFAULT NULL COMMENT 'Timestamp from VIDA webhook confirmation',
  `signed_file_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '/var/app/storage/contracts/{year}/{month}/{application_id}_signed.pdf',
  `generated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_contract_documents_application` (`application_id`),
  KEY `idx_contract_sign_status` (`sign_status`),
  CONSTRAINT `fk_contract_documents_application` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
