CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `actor_type` enum('customer','internal_user','system') COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UUID of customer or internal_user, null for system',
  `actor_username` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Snapshot — not a FK',
  `actor_role` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Snapshot of role at time of action',
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'Human-readable summary of the event',
  `entity_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'e.g. application, internal_user, system_config',
  `entity_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UUID or key of the affected record',
  `old_value` json DEFAULT NULL COMMENT 'State before the change',
  `new_value` json DEFAULT NULL COMMENT 'State after the change',
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `request_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Correlation ID from HTTP header X-Request-ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_actor_id` (`actor_id`),
  KEY `idx_audit_logs_action` (`action`),
  KEY `idx_audit_logs_entity` (`entity_type`,`entity_id`),
  KEY `idx_audit_logs_created` (`created_at`),
  KEY `idx_audit_entity_created` (`entity_type`,`entity_id`,`created_at`),
  KEY `idx_audit_actor_created` (`actor_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_actions` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `application_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'internal_users.id',
  `actor_username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Snapshot at time of action — survives user deletion',
  `actor_role` enum('admin','supervisor','operator') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Snapshot of role at time of action',
  `action` enum('OPENED','RECOMMENDED','APPROVED','REJECTED','NOTE_ADDED','REOPENED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci COMMENT 'Mandatory for REJECTED and NOTE_ADDED actions',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_review_actions_application` (`application_id`),
  KEY `idx_review_actions_actor` (`actor_id`),
  KEY `idx_review_actions_action` (`action`),
  KEY `idx_review_actions_created` (`created_at`),
  KEY `idx_review_actor_action` (`actor_id`,`action`,`created_at`),
  CONSTRAINT `fk_review_actions_actor` FOREIGN KEY (`actor_id`) REFERENCES `internal_users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_review_actions_application` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `webhook_events` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'vida' COMMENT 'Origin system sending the webhook',
  `event_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'e.g. document.signed, document.expired',
  `application_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vida_event_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'VIDA unique event ID for idempotency — check before processing',
  `payload` json NOT NULL,
  `processed` tinyint(1) NOT NULL DEFAULT '0',
  `processed_at` datetime DEFAULT NULL,
  `process_attempts` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Incremented on each processing attempt',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Last processing error if any',
  `received_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_webhook_events_vida_event_id` (`vida_event_id`),
  KEY `idx_webhook_events_application` (`application_id`),
  KEY `idx_webhook_events_processed` (`processed`),
  KEY `idx_webhook_events_event_type` (`event_type`),
  KEY `idx_webhook_events_received` (`received_at`),
  KEY `idx_webhook_unprocessed` (`processed`,`process_attempts`,`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notification_logs` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `application_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel` enum('EMAIL','WHATSAPP') COLLATE utf8mb4_unicode_ci NOT NULL,
  `recipient` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Email address or WhatsApp phone number (with country code)',
  `template` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Template identifier, e.g. esign_link_email',
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Email subject line (null for WhatsApp)',
  `status` enum('PENDING','SENT','FAILED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `provider_message_id` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Message ID returned by Email/WA provider',
  `sent_at` datetime DEFAULT NULL,
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT 'Provider error response if status = FAILED',
  `retry_count` tinyint unsigned NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notification_logs_application` (`application_id`),
  KEY `idx_notification_logs_channel` (`channel`),
  KEY `idx_notification_logs_status` (`status`),
  KEY `idx_notif_status_retry` (`status`,`retry_count`,`created_at`),
  CONSTRAINT `fk_notification_logs_application` FOREIGN KEY (`application_id`) REFERENCES `applications` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
